# Generated by Django 4.0.2 on 2022-06-19 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('year_in_school', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Different')], max_length=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('cred_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_ref', models.BinaryField()),
                ('password_ref', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.users')),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
    ]
