# Generated by Django 4.0.2 on 2022-06-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('results_num', models.IntegerField()),
            ],
            options={
                'db_table': 'search_items',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('results_clicks_num', models.IntegerField()),
                ('marketing_clicks_num', models.IntegerField()),
                ('pages_viewed_num', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search_backend.searchitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.users')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
