# Generated by Django 4.0.2 on 2022-06-22 17:38

from django.db import migrations, models
import search_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('search_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureSearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=search_backend.models.picture_path)),
                ('question', models.TextField()),
            ],
            options={
                'db_table': 'picture_search_items',
            },
        ),
    ]
