version: "3.9"

services:
  # bubuntu:
  #   image: ubuntu:jammy
  #   command: tail -F anything
  #   networks:
  #     - asc_network

  ascapp:
    image: asc_app
    environment:
      - DEPLOYED=1
    build:
      context: ../
      dockerfile: lab06/django_app.dockerfile
    networks:
      - asc_network
    depends_on:
      - postgres
    secrets:
      - db_name
      - db_usr
      - db_pwd
    ports:
      - "8000:8000"

  nginx:
    image: asc_nginx
    build:
      context: ./
      dockerfile: ./nginx.dockerfile
    networks:
      - asc_network
    depends_on:
      - ascapp
    ports:
      - "8008:8008"

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB_FILE: "/run/secrets/db_name"
      POSTGRES_USER_FILE: "/run/secrets/db_usr"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_pwd"
    networks:
      - asc_network
    secrets:
      - db_name
      - db_usr
      - db_pwd

networks:
  asc_network:
    external:
      name: "asc_overlay"

secrets:
  db_name:
    file: name
  db_usr:
    file: usr
  db_pwd:
    file: pwd
